<?php 
	include_once('../top.php');
	require_once('OAuth.php');
	require_once('../db/dbconnector.php');
	
	if($_POST['api'])
		$api = 'http://demo.pesapal.com';
	else
		$api = 'https://www.pesapal.com';
	
	$token = $params 	= NULL;
	$iframelink 		= $api.'/api/PostPesapalDirectOrderV4';
	
	//Kenyan keys
	$consumer_key 		= ""; 
	$consumer_secret 	= "";
	 
	$signature_method	= new OAuthSignatureMethod_HMAC_SHA1();
	$consumer 			= new OAuthConsumer($consumer_key, $consumer_secret);
	
	//get form details
	if(!$_POST['reference']){
		$ref				=  str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',5);
		$_POST['reference']	=  substr(str_shuffle($ref),0,10);
	}
	
	$amount 		= str_replace(',','',$_POST['amount']); // remove thousands seperator if included
	$amount 		= number_format($amount, 2); //format amount to 2 decimal places
	$desc 			= $_POST['description'];
	$type 			= 'MERCHANT';	
	$first_name 	= $_POST['first_name'];
	$last_name 		= $_POST['last_name'];
	$email 			= $_POST['email'];
	$phonenumber	= $_POST['phone_number'];
	$currency 		= $_POST['currency'];
	$reference 		= $_POST['reference']; //unique transaction id, generated by merchant.
	$callback_url 	= '[domain]/pesapalPHPExample/redirect.php'; //URL user to be redirected to after payment
	
	//Record order in your database.
	$database = new pesapalDatabase();
	$database->store($_POST); 
		
	$post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
				   <PesapalDirectOrderInfo 
						xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" 
					  	xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" 
					  	Currency=\"".$currency."\" 
					  	Amount=\"".$amount."\" 
					  	Description=\"".$desc."\" 
					  	Type=\"".$type."\" 
					  	Reference=\"".$reference."\" 
					  	FirstName=\"".$first_name."\" 
					  	LastName=\"".$last_name."\" 
					  	Email=\"".$email."\" 
					  	PhoneNumber=\"".$phonenumber."\" 
					  	xmlns=\"http://www.pesapal.com\" />";
	$post_xml = htmlentities($post_xml);
	
	//post transaction to pesapal
	$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
	$iframe_src->set_parameter("oauth_callback", $callback_url);
	$iframe_src->set_parameter("pesapal_request_data", $post_xml);
	$iframe_src->sign_request($signature_method, $consumer, $token);
	
	include('../pay.php');
	include_once('../top.php'); 
?>  